```{r}
devtools::load_all(".")
library("scMultiSim")
```

## Generate config list

```{r}
ROOT_DIR <- "/home/[USER]/scMultiSim/bench/a"

.ds_A_name <- function(conf, fn = NULL) {
  dis_str <- if (conf$dis) "dis_" else "cnt_"
  out_dir <- sprintf("%stree_%d_velo_%g_af_%g_diff_%g_intr_%g_sig_%g_seed_%d",
                     dis_str, conf$tree, conf$velo, conf$af, conf$diff, conf$intr, conf$sigma, conf$seed)
  path <- file.path(ROOT_DIR, out_dir)
  dir.create(path, showWarnings = F, recursive = T)
  if (is.null(fn)) {
    path
  } else {
    file.path(path, fn)    
  }
}

af_list <- c(0.2, 0.5, 0.9)
configs_a <- expand.grid(
  velo = F,
  tree = 5,
  af = af_list,
  intr = c(0.3, 1),
  diff = c(0.8, 0.2),
  dis = c(T, F),
  sigma = c(0.1, 0.5, 1),
  seed = 1:2
) %>% split(., seq(nrow(.)))
```

# Simulation

```{r}
library(doParallel)
registerDoParallel(cores = 8)

foreach (conf = configs_a) %dopar% {
  options_ <- list2(
    rand.seed = conf$seed,
    atac.effect = conf$af,
    GRN = GRN_params_100,
    num.genes = 200,
    num.cells = 1000,
    num.cifs = 50,
    tree = Phyla5(),
    discrete.cif = conf$dis,
    cif.sigma = conf$sigma,
    diff.cif.fraction = conf$diff,
    do.velocity = F,
    intrinsic.noise = conf$intr,
  )
  res <- sim_true_counts(options_)
  saveRDS(res, .ds_A_name(conf, "res.rds"))
}

```